import RemoveRedEye from 'material-ui/svg-icons/image/remove-red-eye';
import PersonAdd from 'material-ui/svg-icons/social/person-add';
import ContentLink from 'material-ui/svg-icons/content/link';
import ContentCopy from 'material-ui/svg-icons/content/content-copy';
const menuitems = [
  {
    list:{
    },
    name:"page1",
    label:"普通查询",
    icon:RemoveRedEye,
  },
  {
    list:{
    },
    name:"page2",
    label:"跨域查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page3",
    label:"restfulapi",
    icon:ContentLink,
  },
  {
    list:{
    },
    name:"flexpage",
    label:"flex 布局演练",
    icon:ContentCopy,
  },
  {
    list:{
    },
    name:"page4",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page5",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page6",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page7",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page8",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page9",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page10",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page11",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page12",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page13",
    label:"jsonp查询",
    icon:PersonAdd,
  },
  {
    list:{
    },
    name:"page14",
    label:"jsonp查询",
    icon:PersonAdd,
  }
];
export default menuitems;
